# Essa configuração não está sendo carregada na hora da instalação 
# mas é executada depois com "drush cim --partial"
langcode: en
anonymous: Anônimo
verify_mail: true
notify:
  cancel_confirm: true
  password_reset: false
  status_activated: true
  status_blocked: false
  status_canceled: false
  register_admin_created: true
  register_no_approval_required: true
  register_pending_approval: true
register: admin_only
cancel_method: user_cancel_block
password_reset_timeout: 86400
password_strength: true
